version: '3'

networks:
  hello-dapr: null

volumes:
  my-db:

configs:
  collector_conf:
    file: ./confs/collector.yml

services:
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - hello-dapr

  #
  #  mysql server bindings
  # 
  # https://hub.docker.com/_/mysql
  db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'dapr'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  ############################
  # tracing
  ############################
  # zipkin:
  #   image: openzipkin/zipkin
  #   ports:
  #     - "9410:9410"
  #     - "9411:9411"
  #   networks:
  #     - hello-dapr

  otel-collector:
    deploy:
      resources:
        limits:
          memory: 125M
    ports:
      # - "4317"          # OTLP over gRPC receiver
      # - "4318"          # OTLP over HTTP receiver
      # - "1888:1888"     # pprof extension
      # - "13133:13133"   # health_check extension
      - "9410:9410"
      - "9411:9411"
    # https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags
    image: otel/opentelemetry-collector-contrib:0.88.0
    configs:
      - source: collector_conf
        target: /conf/collector.yml
    command: ["--config=/conf/collector.yml"]
    networks:
      - hello-dapr
    # https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-environment-attribute
    environment:
      # lightstep stuff
      - INSTRUMENTATION_KEY=${INSTRUMENTATION_KEY}
